
services:

  webserver:

    build:
      context: .
      dockerfile: Dockerfile

    container_name: portfoliopage
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - webnet 

networks:
  webnet:
    driver: bridge
