name: Build and Push Docker Image  

on:
  push:  # Aciona o workflow quando há um push
    branches:
      - main  # Muda para o branch que você está usando para produção

jobs:
  build:  # Nome do trabalho que será executado
    runs-on: ubuntu-latest  # Define que a execução ocorrerá em uma máquina virtual Ubuntu

    steps:  # Define as etapas a serem realizadas no trabalho
      - name: Checkout code  # Nome da etapa
        uses: actions/checkout@v2  # Faz o checkout do repositório para que o código esteja disponível

      - name: Docker Login 
        uses: docker/login-action@v3.3.0
        with:  # Passa os parâmetros para a ação
          username: ${{ secrets.USER }}  # Nome de usuário do Docker Hub armazenado em segredos
          password: ${{ secrets.PASSWD }}  # Senha do Docker Hub armazenada em segredos

      - name: Build and push Docker images 
        uses: docker/build-push-action@v6.8.0 # Usa a ação do Docker para construir e enviar a imagem
        with:  
          context: .  
          push: true
          tags: nilewa/nginx-webserver:latest
